spring.application.name=inmobiliaria
server.port=8080
spring.web.error.include-message=always
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.deserialization.fail-on-null-for-primitives=false
